# Settings for the StealthPlugin
# Plugin created by Unlustig
# 
# If you f****d up this config, then delete it and restart the server, it will than generate a new default one!
#______________________________________________________________________________________________________________

Enable:
# Set to false if you don't want people to use the plugin part
    Suit: true
    Sneak: true
    Stealth: true
    NinjaWeapons: true
#______________________________________________________________________________________________________________
    
Sneak: 
# Set maximum lightlevel in which u can use sneak to go invisible set to -1 if you don't want people to hide
    LightLevel: 6
# Set to 0 if you dont want bonus damage for sneak attacks (attack out of sneak-invisiblity)
    Damage: 0
# set to true if you want sneak-hidden players to see other hidden players
    Detection: false
# set the time in which you are visible after attacking out of stealth
    Cooldown: 10
#______________________________________________________________________________________________________________

Stealth:   
# set the maximum lightlevel in which players are ALWAYS invisible
# set to -1 if u don't want players to be always invisible
    LightLevel: 0
# Set to 0 if you dont want bonus damage for stealth attacks (attack out of stealth-invisiblity)
    Damage: 0
# set to true if you want Stealth-hidden players to see other hidden players
    Detection: false
# set the time in which you are visible after attacking out of stealth
    Cooldown: 5
#______________________________________________________________________________________________________________

Suit:
# Set to false if you don't want the ninja suit to break faster by hiding with it.
    Damage: true
# Set to false if you want players with a ninja suit to be always invisible (disables Cooldown)
    OnSneak: true
# Time it takes before a player can use ninja-suit again.
    Cooldown: 120
# Maximum time a player can use stealth with ninja-suit before getting visible again.
    Duration: 30
        
    Messages:
# Add the messages u want to show when the suit is on cooldown and a player tries to hide ('' for no message)
        StartCooldown: '&cThe Ninja-Suit is now on cooldown!'
        Cooldown: '&cNinja-Suit is still on cooldown!'
        EndCooldown: '&2Ninja-Suit can now be used again!'
    Equip:
# -The plugin checks for the name, the id and the color, only if all are euiped by a player he can use the suit stealth
# -Use -1 as Id if the player can have ANY item in that slot (0 for empty slot) (0 and -1 will ignore color and name for that item)
# -Use 'any' if you dont want to check for the name (use & for colorcodes)
# -Use 'any' if you dont want to check for the color of leather armor (otherwise the syntax is '<R>,<G>,<B>')
        Helmet:
            Id: 298
            Name: '&4Ninja Hood'
            Color: '0,0,0'
        Chestplate:
            Id: 299
            Name: '&4Ninja Top'
            Color: '0,0,0'
        Leggings:
            Id: 300
            Name: '&4Ninja Pants'
            Color: '0,0,0'
        Boots:
            Id: 301
            Name: '&4Ninja Tabi'
            Color: '0,0,0'
#___________________________________________________________________________________________________________

NinjaWeapons:
    Sword:
# -1 = any(will ignore name) , 0 = hand(will ignore name), -2 = any kind of sword (wooden, stone, iron, diamond, gold)
# -Use 'any' if you dont want to check for the name (use & for colorcodes)
        Id: -2
        Name: '&4Demon Katana'
    Bow:
        Name: 'any'
#___________________________________________________________________________________________________________

Misc: 
# Set the messages, write '' for no message
        StealthActivate: '&2Stealth activated!'
        StealthDeactivated: '&cStealth deactivated!'
        