name: StealthPlugin
main: com.github.unlustig.StealthPlugin.Main
version: 0.1.1
description: A Stealth Plugin containing many forms of stealth!
author: Unlusig
website: //TODO
softdepend: //TODO

permissions:
    StealthPlugin.seeInvisibile:
       desrciption: Allows you to see hidden players
       default: op
    StealthPlugin.admin:
       description: Allows you to use the /StealthPlugin command
       default: op
    StealthPlugin.hide.*:
       description: Allows you to hide with every implemented form of stealth
       children:
          StealthPlugin.hide.suit
          StealthPlugin.hide.lowlight
          StealthPlugin.hide.sneak
    StealthPlugin.hide.suit:
       description: Allows you to hide with a "ninja-suit"
       default: true
    StealthPlugin.hide.lowlight
       description: Your name will be hidden if you are in an area with a low lightlevel
       default: true
    StealthPlugin.hide.sneak
       description: Allows you to hide yourself if you sneak in an area with really low lightlevel
       default: true

commands: 
   StealthPlugin: 
      description: The StealthPlugin general command.
      usage: 
         /&lt;<command>&gt; - Shows this help.
         /&lt;<command>&gt; reset - resets the cooldown on your invisibility
         /&lt;<command>&gt; reload - reloads the config.yml
      permission: StealthPlugin.admin
      permission-massage: You don't have the <permission> perm!
      aliases: [sp, stealth_plugin]
      